[package]
name = "cairo-lang-syntax"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Cairo syntax representation."

[dependencies]
cairo-lang-debug = { path = "../cairo-lang-debug", version = "~2.13.1" }
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "~2.13.1" }
cairo-lang-primitive-token.workspace = true
<<<<<<< HEAD
cairo-lang-proc-macros = { path = "../cairo-lang-proc-macros", version = "~2.13.0" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "~2.13.0", features = ["tracing"] }
||||||| 8bebf62e2
cairo-lang-utils = { path = "../cairo-lang-utils", version = "~2.13.0", features = ["tracing"] }
=======
cairo-lang-utils = { path = "../cairo-lang-utils", version = "~2.13.1", features = ["tracing"] }
>>>>>>> origin/dev-v2.13.1
num-bigint = { workspace = true, default-features = true }
num-traits = { workspace = true, default-features = true }
salsa.workspace = true
serde = { workspace = true, default-features = true }
unescaper.workspace = true
vector-map.workspace = true

[dev-dependencies]
cairo-lang-test-utils = { path = "../cairo-lang-test-utils", features = ["testing"] }
pretty_assertions.workspace = true
tracing.workspace = true
