[package]
name = "cairo-lang-eq-solver"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Equation solving for Sierra generation."

[dependencies]
<<<<<<< HEAD
cairo-lang-utils = { path = "../cairo-lang-utils", version = "~2.12.0", features = ["tracing"] }
||||||| c9743105f
cairo-lang-utils = { path = "../cairo-lang-utils", version = "~2.12.0" }
=======
cairo-lang-utils = { path = "../cairo-lang-utils", version = "~2.12.1" }
>>>>>>> origin/dev-v2.12.1
good_lp.workspace = true

[dev-dependencies]
cairo-lang-test-utils = { path = "../cairo-lang-test-utils", features = ["testing"] }
tracing.workspace = true
