[package]
name = "cairo-lang-doc"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "A collection of documentation processing utilities for the Cairo programming language."

[dependencies]
<<<<<<< HEAD
cairo-lang-debug = { path = "../cairo-lang-debug", version = "~2.12.0" }
cairo-lang-defs = { path = "../cairo-lang-defs", version = "~2.12.0" }
cairo-lang-diagnostics = { path = "../cairo-lang-diagnostics", version = "~2.12.0" }
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "~2.12.0" }
cairo-lang-formatter = { path = "../cairo-lang-formatter", version = "~2.12.0" }
cairo-lang-parser = { path = "../cairo-lang-parser", version = "~2.12.0" }
cairo-lang-semantic = { path = "../cairo-lang-semantic", version = "~2.12.0" }
cairo-lang-syntax = { path = "../cairo-lang-syntax", version = "~2.12.0" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "~2.12.0", features = ["tracing"] }
itertools.workspace = true
||||||| c9743105f
cairo-lang-defs = { path = "../cairo-lang-defs", version = "~2.12.0" }
cairo-lang-parser = { path = "../cairo-lang-parser", version = "~2.12.0" }
cairo-lang-syntax = { path = "../cairo-lang-syntax", version = "~2.12.0" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "~2.12.0" }
cairo-lang-semantic = { path = "../cairo-lang-semantic", version = "~2.12.0" }
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "~2.12.0" }
cairo-lang-formatter = { path = "../cairo-lang-formatter", version = "~2.12.0" }
cairo-lang-diagnostics = { path = "../cairo-lang-diagnostics", version ="~2.12.0"}
cairo-lang-debug = { path = "../cairo-lang-debug", version ="~2.12.0" }
smol_str.workspace = true
=======
cairo-lang-defs = { path = "../cairo-lang-defs", version = "~2.12.1" }
cairo-lang-parser = { path = "../cairo-lang-parser", version = "~2.12.1" }
cairo-lang-syntax = { path = "../cairo-lang-syntax", version = "~2.12.1" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "~2.12.1" }
cairo-lang-semantic = { path = "../cairo-lang-semantic", version = "~2.12.1" }
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "~2.12.1" }
cairo-lang-formatter = { path = "../cairo-lang-formatter", version = "~2.12.1" }
cairo-lang-diagnostics = { path = "../cairo-lang-diagnostics", version ="~2.12.1"}
cairo-lang-debug = { path = "../cairo-lang-debug", version ="~2.12.1" }
smol_str.workspace = true
>>>>>>> origin/dev-v2.12.1
pulldown-cmark = "0.13.0"
salsa.workspace = true

[dev-dependencies]
anyhow.workspace = true
cairo-lang-semantic = { path = "../cairo-lang-semantic" }
cairo-lang-test-utils = { path = "../cairo-lang-test-utils", features = ["testing"] }
indoc.workspace = true
tracing.workspace = true
