[package]
name = "sierra-compile"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Compiler executable for the Sierra intermediate representation"

[dependencies]
anyhow.workspace = true
clap.workspace = true
indoc.workspace = true
log.workspace = true
tracing.workspace = true

<<<<<<< HEAD
cairo-lang-sierra = { path = "../../cairo-lang-sierra", version = "~2.12.0" }
cairo-lang-sierra-to-casm = { path = "../../cairo-lang-sierra-to-casm", version = "~2.12.0" }
cairo-lang-sierra-type-size = { path = "../../cairo-lang-sierra-type-size", version = "~2.12.0" }
cairo-lang-utils = { path = "../../cairo-lang-utils", version = "~2.12.0", features = ["tracing"] }
||||||| c9743105f
cairo-lang-sierra = { path = "../../cairo-lang-sierra", version = "~2.12.0" }
cairo-lang-sierra-to-casm = { path = "../../cairo-lang-sierra-to-casm", version = "~2.12.0" }
cairo-lang-utils = { path = "../../cairo-lang-utils", version = "~2.12.0", features = [
    "env_logger",
] }
=======
cairo-lang-sierra = { path = "../../cairo-lang-sierra", version = "~2.12.1" }
cairo-lang-sierra-to-casm = { path = "../../cairo-lang-sierra-to-casm", version = "~2.12.1" }
cairo-lang-utils = { path = "../../cairo-lang-utils", version = "~2.12.1", features = [
    "env_logger",
] }
>>>>>>> origin/dev-v2.12.1
