[package]
name = "cairo-format"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Cairo formatter executable for the Cairo programming language"

[dependencies]
clap.workspace = true
colored.workspace = true
ignore.workspace = true
log.workspace = true
tracing.workspace = true

<<<<<<< HEAD
cairo-lang-formatter = { path = "../../cairo-lang-formatter", version = "~2.12.2" }
cairo-lang-utils = { path = "../../cairo-lang-utils", version = "~2.12.2", features = ["tracing"] }
||||||| a668b7cd1
cairo-lang-formatter = { path = "../../cairo-lang-formatter", version = "~2.12.2" }
cairo-lang-utils = { path = "../../cairo-lang-utils", version = "~2.12.2", features = [
    "env_logger",
] }
=======
cairo-lang-formatter = { path = "../../cairo-lang-formatter", version = "~2.12.3" }
cairo-lang-utils = { path = "../../cairo-lang-utils", version = "~2.12.3", features = [
    "env_logger",
] }
>>>>>>> dev-v2.12.3
