[package]
name = "cairo-run"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Runner executable for the Cairo programming language"

[dependencies]
anyhow.workspace = true
clap.workspace = true
mimalloc = { workspace = true, optional = true }

<<<<<<< HEAD
cairo-lang-compiler = { path = "../../cairo-lang-compiler", version = "~2.13.0" }
cairo-lang-diagnostics = { path = "../../cairo-lang-diagnostics", version = "~2.13.0" }
cairo-lang-filesystem = { path = "../../cairo-lang-filesystem", version = "~2.13.0" }
cairo-lang-runner = { path = "../../cairo-lang-runner", version = "~2.13.0" }
cairo-lang-sierra-generator = { path = "../../cairo-lang-sierra-generator", version = "~2.13.0" }
cairo-lang-starknet = { path = "../../cairo-lang-starknet", version = "~2.13.0" }

[features]
mimalloc = ["dep:mimalloc"]
||||||| 8bebf62e2
cairo-lang-compiler = { path = "../../cairo-lang-compiler", version = "~2.13.0" }
cairo-lang-diagnostics = { path = "../../cairo-lang-diagnostics", version = "~2.13.0" }
cairo-lang-filesystem = { path = "../../cairo-lang-filesystem", version = "~2.13.0" }
cairo-lang-runner = { path = "../../cairo-lang-runner", version = "~2.13.0" }
cairo-lang-sierra-generator = { path = "../../cairo-lang-sierra-generator", version = "~2.13.0" }
cairo-lang-starknet = { path = "../../cairo-lang-starknet", version = "~2.13.0" }
=======
cairo-lang-compiler = { path = "../../cairo-lang-compiler", version = "~2.13.1" }
cairo-lang-diagnostics = { path = "../../cairo-lang-diagnostics", version = "~2.13.1" }
cairo-lang-filesystem = { path = "../../cairo-lang-filesystem", version = "~2.13.1" }
cairo-lang-runner = { path = "../../cairo-lang-runner", version = "~2.13.1" }
cairo-lang-sierra-generator = { path = "../../cairo-lang-sierra-generator", version = "~2.13.1" }
cairo-lang-starknet = { path = "../../cairo-lang-starknet", version = "~2.13.1" }
>>>>>>> origin/dev-v2.13.1
