[package]
name = "cairo-lang-debug"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Debug utilities for query objects."

[dependencies]
<<<<<<< HEAD
cairo-lang-utils = { path = "../cairo-lang-utils", version = "~2.12.2", features = ["tracing"] }
id-arena.workspace = true
salsa.workspace = true
||||||| a668b7cd1
cairo-lang-utils = { path = "../cairo-lang-utils", version = "~2.12.2" }
=======
cairo-lang-utils = { path = "../cairo-lang-utils", version = "~2.12.3" }
>>>>>>> dev-v2.12.3

[dev-dependencies]
cairo-lang-proc-macros = { path = "../cairo-lang-proc-macros" }
cairo-lang-test-utils = { path = "../cairo-lang-test-utils", features = ["testing"] }
tracing.workspace = true
