[crate_roots]
core = "src"

[config.global]
<<<<<<< HEAD
||||||| c9743105f
version = "2.12.0"
=======
version = "2.12.1"
>>>>>>> origin/dev-v2.12.1
edition = "2024_07"
version = "2.12.0"

[config.global.experimental_features]
associated_item_constraints = true
coupons = true
negative_impls = true
user_defined_inline_macros = true
