[crate_roots]
core = "src"

[config.global]
<<<<<<< HEAD
||||||| e07531d91
version = "2.12.1"
=======
version = "2.12.2"
>>>>>>> origin/dev-v2.12.2
edition = "2024_07"
version = "2.12.1"

[config.global.experimental_features]
associated_item_constraints = true
coupons = true
negative_impls = true
user_defined_inline_macros = true
